In [23]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

### Directory and File Path

In [24]:
ROOT_DIR=Path.cwd().parent
DATA_DIR= ROOT_DIR / "03_assignment" / "data"
CSV_FILE= DATA_DIR / "car_clean_dataset.csv"

### Load Dataset

In [25]:
df = pd.read_csv(CSV_FILE)
df = df.drop(columns=["Unnamed: 0"])
df.head(5)

,Price,Odometer_km,Doors,Accidents,Year,Location_city,Location_rural,Location_suburb,Car_Age,Km_per_year,Is_Urban,LogPrice
0,1500.0,0.128390,0.254091,0.316968,-1.686714,1,0,0,1.686714,-0.615631,1,7.313887
1,4171.0,-0.044709,0.254091,-0.820867,0.794617,0,1,0,-0.794617,0.070446,0,8.336151
2,5331.0,-0.440923,0.254091,-0.820867,0.518913,0,0,1,-0.518913,-0.267993,0,8.581482
3,1500.0,0.203135,0.254091,0.316968,-1.548862,0,0,1,1.548862,-0.587024,0,7.313887
4,1500.0,-0.044709,-0.931668,-0.820867,1.621727,1,0,0,-1.621727,1.738196,1,7.313887

### Prepare Features & Target

In [26]:
df.columns

Index(['Price', 'Odometer_km', 'Doors', 'Accidents', 'Year', 'Location_city',
       'Location_rural', 'Location_suburb', 'Car_Age', 'Km_per_year',
       'Is_Urban', 'LogPrice'],
      dtype='object')

In [27]:
X = df[['Car_Age','Accidents','Km_per_year','Is_Urban']]
y = df['Price']
X.head()

    Car_Age  Accidents  Km_per_year  Is_Urban
0  1.686714   0.316968    -0.615631         1
1 -0.794617  -0.820867     0.070446         0
2 -0.518913  -0.820867    -0.267993         0
3  1.548862   0.316968    -0.587024         0
4 -1.621727  -0.820867     1.738196         1

In [28]:
y

0      1500.0
1      4171.0
2      5331.0
3      1500.0
4      1500.0
        ...
135    1500.0
136    1500.0
137    1500.0
138    1500.0
139    1500.0
Name: Price, Length: 140, dtype: float64

### Split Data

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
X_train.head()

      Car_Age  Accidents  Km_per_year  Is_Urban
16  -1.208172   0.316968    -0.039047         1
18  -1.483875  -0.820867     0.001564         1
10   0.446049  -0.820867    -0.460067         0
111  0.170345  -0.820867     0.198583         1
101  1.273159   0.316968    -0.585776         1

In [31]:
X_test.head()

      Car_Age  Accidents  Km_per_year  Is_Urban
108 -0.381062   0.316968    -0.456483         1
67  -1.483875   1.454804     1.111045         0
31  -0.656765   1.454804     0.303315         1
119 -1.208172  -0.820867     0.197668         1
42   0.859604  -0.820867    -0.242703         0

In [32]:
print(y_train)
print(y_test)

16     8638.000
18     8974.375
10     1500.000
111    1500.000
101    1500.000
         ...
71     1500.000
106    1500.000
14     1500.000
92     8974.375
102    1500.000
Name: Price, Length: 112, dtype: float64
108    4379.000
67     5732.000
31     1500.000
119    7009.000
42     1500.000
12     3622.000
81     1500.000
69     8974.375
104    1500.000
109    1500.000
113    8950.000
56     1500.000
66     1500.000
19     6260.000
132    6185.000
78     1500.000
11     8974.375
27     3892.000
127    1500.000
110    1500.000
36     3444.000
118    1500.000
60     1500.000
4      1500.000
131    3497.000
26     1500.000
138    1500.000
96     1500.000
Name: Price, dtype: float64

In [33]:
poly = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

### Train Models

In [34]:
lr = LinearRegression()

In [35]:
lr.fit(X_train_poly,y_train)

LinearRegression()

In [36]:
lr_y_predicted = lr.predict(X_test_poly)

In [37]:
pd.DataFrame({'lr_y_predict':lr_y_predicted,'y_true':y_test.to_list()})

    lr_y_predict    y_true
0    4563.185484  4379.000
1    5759.097264  5732.000
2    2146.856986  1500.000
3    6805.669034  7009.000
4     -45.194833  1500.000
5    3815.946222  3622.000
6    2016.004155  1500.000
7    2643.996870  8974.375
8    1900.762129  1500.000
9    1458.334082  1500.000
10   5976.718090  8950.000
11   2023.846795  1500.000
12   2620.281974  1500.000
13   5513.494921  6260.000
14   5335.320676  6185.000
15   3385.000256  1500.000
16   8016.575089  8974.375
17   3665.837628  3892.000
18   2457.049627  1500.000
19   2254.430637  1500.000
20   5656.608775  3444.000
21   1131.463170  1500.000
22     72.993882  1500.000
23   5465.538595  1500.000
24   4790.300969  3497.000
25    293.167215  1500.000
26   1304.456115  1500.000
27   1025.745745  1500.000

In [38]:
rf = RandomForestRegressor(n_estimators=100,random_state=42)

In [39]:
rf.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [40]:
rf_y_predicted = rf.predict(X_test)

In [41]:
pd.DataFrame({'rf_y_predict':rf_y_predicted,'y_true':y_test.to_list()})

    rf_y_predict    y_true
0     4867.52500  4379.000
1     6711.48375  5732.000
2     1794.87750  1500.000
3     7751.24625  7009.000
4     1500.00000  1500.000
5     3495.96375  3622.000
6     1653.60000  1500.000
7     3043.08250  8974.375
8     1500.00000  1500.000
9     1820.84375  1500.000
10    5517.49125  8950.000
11    1573.41000  1500.000
12    1571.19000  1500.000
13    6725.61375  6260.000
14    3264.89875  6185.000
15    1552.70000  1500.000
16    7332.52000  8974.375
17    3862.16000  3892.000
18    1584.76000  1500.000
19    1538.41000  1500.000
20    5968.00250  3444.000
21    1500.00000  1500.000
22    1500.00000  1500.000
23    6792.79875  1500.000
24    6880.43750  3497.000
25    3530.10500  1500.000
26    1500.00000  1500.000
27    1500.00000  1500.000

### Evaluate Performance

In [42]:
def print_performance_metrics(name:str,y_true:pd.Series,y_predict:np.ndarray):
    r2 = r2_score(y_true,y_predict)
    mae = mean_absolute_error(y_true,y_predict)
    mse = mean_squared_error(y_true,y_predict)
    rmse = np.sqrt(mse)

    print(f"Performance of {name}")
    print("R2:",f"{r2:.2f}")
    print("MAE:",f"{mae:.2f}")
    print("MSE:",f"{mse:.2f}")
    print("RMSE:",f"{rmse:.2f}")

In [43]:
print_performance_metrics("Linear Regression",y_test,lr_y_predicted)
print_performance_metrics("Random Forest Regression",y_test,rf_y_predicted)

Performance of Linear Regression
R2: 0.53
MAE: 1150.97
MSE: 3116551.15
RMSE: 1765.38
Performance of Random Forest Regression
R2: 0.41
MAE: 1109.92
MSE: 3941294.13
RMSE: 1985.27

In [44]:
print_performance_metrics("Random Forest train",y_train,rf.predict(X_train))
print_performance_metrics("Linear Regression train",y_train,lr.predict(X_train_poly))

Performance of Random Forest train
R2: 0.91
MAE: 461.95
MSE: 580472.04
RMSE: 761.89
Performance of Linear Regression train
R2: 0.65
MAE: 1205.07
MSE: 2377305.45
RMSE: 1541.85