In [11]:
import pandas as pd

df = pd.read_csv("data/clean_loan_dataset.csv")
# df.head()

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.585174,0.121560,0.024490,0.339800,1,0,0,0.237111,51814.285714
1,0.498215,0.091743,0.591837,0.101287,1,0,1,0.116084,6030.125000
2,0.018530,0.353211,0.200000,0.115989,0,0,1,0.424889,4449.687500
3,0.000000,0.176606,0.697959,0.032673,1,0,1,0.270783,1389.838710
4,0.088490,0.098624,0.379592,0.093118,0,0,1,0.278675,3555.185185

In [4]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
df.head()

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.585174,0.121560,0.024490,0.339800,1,0,0,0.237111,51814.285714
1,0.498215,0.091743,0.591837,0.101287,1,0,1,0.116084,6030.125000
2,0.018530,0.353211,0.200000,0.115989,0,0,1,0.424889,4449.687500
3,0.000000,0.176606,0.697959,0.032673,1,0,1,0.270783,1389.838710
4,0.088490,0.098624,0.379592,0.093118,0,0,1,0.278675,3555.185185

In [5]:
# Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

lr = LogisticRegression(max_iter=1000)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
dt = DecisionTreeClassifier(random_state=42)

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.585174,0.121560,0.024490,0.339800,1,0,0,0.237111,51814.285714
1,0.498215,0.091743,0.591837,0.101287,1,0,1,0.116084,6030.125000
2,0.018530,0.353211,0.200000,0.115989,0,0,1,0.424889,4449.687500
3,0.000000,0.176606,0.697959,0.032673,1,0,1,0.270783,1389.838710
4,0.088490,0.098624,0.379592,0.093118,0,0,1,0.278675,3555.185185

In [6]:
# Train Models
lr.fit(X_train, y_train)
rf.fit(X_train, y_train)
dt.fit(X_train, y_train)
# df.head()

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.585174,0.121560,0.024490,0.339800,1,0,0,0.237111,51814.285714
1,0.498215,0.091743,0.591837,0.101287,1,0,1,0.116084,6030.125000
2,0.018530,0.353211,0.200000,0.115989,0,0,1,0.424889,4449.687500
3,0.000000,0.176606,0.697959,0.032673,1,0,1,0.270783,1389.838710
4,0.088490,0.098624,0.379592,0.093118,0,0,1,0.278675,3555.185185

In [7]:
# Evaluation Function
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def evaluate(model):
    pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, pred))
    print("Precision:", precision_score(y_test, pred))
    print("Recall:", recall_score(y_test, pred))
    print("F1 Score:", f1_score(y_test, pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, pred))
    print("-"*40)
    # df.head()

In [8]:
# Results
print("Logistic Regression")
evaluate(lr)

print("Random Forest")
evaluate(rf)

print("Decision Tree")
evaluate(dt)
# df.head()

Logistic Regression
Accuracy: 0.6
Precision: 0.631578947368421
Recall: 0.9230769230769231
F1 Score: 0.75
Confusion Matrix:
 [[ 0  7]
 [ 1 12]]
----------------------------------------
Random Forest
Accuracy: 0.65
Precision: 0.7142857142857143
Recall: 0.7692307692307693
F1 Score: 0.7407407407407407
Confusion Matrix:
 [[ 3  4]
 [ 3 10]]
----------------------------------------
Decision Tree
Accuracy: 0.7
Precision: 0.7058823529411765
Recall: 0.9230769230769231
F1 Score: 0.8
Confusion Matrix:
 [[ 2  5]
 [ 1 12]]
----------------------------------------

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.585174,0.121560,0.024490,0.339800,1,0,0,0.237111,51814.285714
1,0.498215,0.091743,0.591837,0.101287,1,0,1,0.116084,6030.125000
2,0.018530,0.353211,0.200000,0.115989,0,0,1,0.424889,4449.687500
3,0.000000,0.176606,0.697959,0.032673,1,0,1,0.270783,1389.838710
4,0.088490,0.098624,0.379592,0.093118,0,0,1,0.278675,3555.185185

In [10]:
# Sanity Check
i = 0

print("Actual:", y_test.iloc[i])
print("LR:", lr.predict(X_test.iloc[[i]])[0])
print("RF:", rf.predict(X_test.iloc[[i]])[0])
print("DT:", dt.predict(X_test.iloc[[i]])[0])
df.head()

Actual: 1
LR: 0
RF: 0
DT: 1

,Income,CreditScore,EmploymentYears,LoanAmount,HasCollateral,PreviousDefaults,Approved,DebtToIncome,IncomePerYearEmployed
0,0.585174,0.121560,0.024490,0.339800,1,0,0,0.237111,51814.285714
1,0.498215,0.091743,0.591837,0.101287,1,0,1,0.116084,6030.125000
2,0.018530,0.353211,0.200000,0.115989,0,0,1,0.424889,4449.687500
3,0.000000,0.176606,0.697959,0.032673,1,0,1,0.270783,1389.838710
4,0.088490,0.098624,0.379592,0.093118,0,0,1,0.278675,3555.185185